### ISSUE TITLE
Error 502 Bad gateway

### ISSUE THREAD

**Issue by Yaknel** [plumageio/magazine#4]
![captura de pantalla 2018-10-04 a las 9 34 02](https://user-images.githubusercontent.com/10654706/46459368-01ed3480-c7b9-11e8-89f9-7dcaae91c32d.png)

The mag is off :( @kremalicious

**Comment by kremalicious** [comment]
it's back up.

note to self:

```bash
sudo apt remove php*
sudo apt install php php-fpm php-mysql

sudo service nginx reload
sudo service php7.2-fpm restart
```

**Comment by Yaknel** [comment]
@kremalicious Matt, it is back again :(
